sudo: false

language: node_js

os:
  - linux

node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  
notifications:
  email: false
